spring:
  application:
    name: usian-item-web
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true #开启降级处理
    command:
      default:
        circuitBreaker:
          requestVolumeThreshold: 3
          errorThresholdPercentage: 5
          sleepWindowInMilliseconds: 5000
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 8000
ribbon:
  ConnectTimeout: 3000 #连接超时时间
  ReadTimeout: 3000 #相应超时时间
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.45.129:22122